<?php

/** @var \M2E\Temu\Block\Adminhtml\Template\Category\Chooser\Tabs\Browse $block */

$isWizard = !$block->viewHelper->isInstallationWizardFinished();

$block->jsUrl->add($block->getUrl('*/general/getChildCategories'), 'general/getChildCategories');

$block->js->add(
    "
require([
    'Temu/Template/Category/Chooser/Tabs/Browse'
], function(){

    window.TemuTemplateCategoryChooserTabsBrowseObj = new TemuTemplateCategoryChooserTabsBrowse();

    TemuTemplateCategoryChooserTabsBrowseObj.setRegion(TemuCategoryChooserObj.getRegion());
    TemuTemplateCategoryChooserTabsBrowseObj.setAccountId(TemuCategoryChooserObj.getAccountId());
    TemuTemplateCategoryChooserTabsBrowseObj.renderTopLevelCategories('chooser_browser-selects');
    TemuTemplateCategoryChooserTabsBrowseObj.observe('leaf_selected', function(selectedCategories) {
        const lastCategory = selectedCategories[selectedCategories.length-1];
        TemuCategoryChooserObj.selectCategory(lastCategory['value']);
    });
});
"
);
?>

<style>
    .category-children-block {
        display: inline-block;
        margin-left: 10px;
    }
</style>

<div id="chooser_browser">
    <div id="chooser_browser-selects"></div>
</div>
