<?php

// @codingStandardsIgnoreFile

/** @var \M2E\Temu\Block\Adminhtml\Renderer\Description\Image $block */

$data = $block->getData();
?>

<style>

    #m2e-description-image-<?php  /* @noEscape */ echo $block->getImageId(); ?> {
    <?php if ($data['width'] != 0) :
        /* @noEscape */ echo "width: {$data['width']}px;";
    endif; ?><?php if ($data['height'] != 0) :
            /* @noEscape */ echo "height: {$data['height']}px;";
        endif; ?><?php if ($data['margin'] != 0) :
            /* @noEscape */ echo "margin-bottom: {$data['margin']}px; margin-right: {$data['margin']}px;";
        endif; ?>
    }

</style>

<img src="<?php
/* @noEscape */ echo $data['src']; ?>"
     border="0"
    <?php
    if ($data['watermark'] != 0) :
        /* @noEscape */ echo ' m2e_watermark="1"';
    endif; ?>
     id="m2e-description-image-<?php
     /* @noEscape */ echo $block->getImageId(); ?>"
/>
