<?php

/** @var \M2E\Temu\Block\Adminhtml\Account\Edit\Form\Render $this */

$isEmptyShippingProvider = empty($this->getShippingProviders());
?>

<style>
    #shipping-mapping-grid td span.required-field:after {
        color: #e22626;
        content: '*';
        display: inline-block;
        font-size: 1.6rem;
        font-weight: 500;
        line-height: 1;
        margin-left: 5px;
    }

    #shipping-mapping-grid tr.new-shop-row:not(:nth-child(1)) {
        border-top: 1px dashed lightgray;
    }
</style>
<table id="shipping-mapping-grid" class="data-grid">
    <thead>
    <tr class="headings">
        <th class="data-grid-th"><?= __('Region') ?></th>
        <th class="data-grid-th"><?= __('Magento Carrier') ?></th>
        <th class="data-grid-th"><?= __(
                '%channel_title Carrier',
                [
                    'channel_title' => \M2E\Temu\Helper\Module::getChannelTitle(),
                ]
            ) ?></th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($this->getRegions() as $region) : ?>
        <?php
        foreach ($this->getMagentoCarriers() as $key => $magentoCarrier) : ?>
            <?= $this->renderTableRow($key, $region, $magentoCarrier) ?>
        <?php
        endforeach; ?>
    <?php
    endforeach; ?>
    </tbody>
</table>

<?php
if ($isEmptyShippingProvider) : ?>
    <p><?= __('To view available shipping carriers, please refresh your account data.') ?></p>
<?php
endif; ?>
